/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Penjahit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ZaFee Tech HP 0099
 */
public class Detail_Penjahit extends javax.swing.JFrame {
    private Penjahit penjahit;    
    private String auth;    
    private String id;


    /**
     * Creates new form Penjahit
     */
    public Detail_Penjahit(String auth, String id) {
        initComponents();
        penjahit = new Penjahit();
        
        this.auth =  auth;        
        this.id =  id;
        input_deskripsi.setEnabled(false);
        penjahit.detail_pesanan(id, tabel_pesanan, input_deskripsi);
        text_nama.setText(penjahit.getNama());
        text_username.setText(penjahit.getUsername());
        text_no_hp.setText(penjahit.getNo_hp());
        text_gender.setText(penjahit.getGender());
        text_alamat.setText(penjahit.getAlamat());
        System.out.println(penjahit.order.getStatus());
        
        if(penjahit.order.getStatus().equals("proses")){
            panel2.setVisible(false);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_pesanan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        input_deskripsi = new javax.swing.JTextArea();
        text_alamat = new javax.swing.JLabel();
        text_nama = new javax.swing.JLabel();
        text_username = new javax.swing.JLabel();
        text_no_hp = new javax.swing.JLabel();
        text_gender = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        button_tolak = new javax.swing.JButton();
        button_terima = new javax.swing.JButton();
        input_harga = new javax.swing.JFormattedTextField();
        button_selesai = new javax.swing.JButton();
        button_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("DESKRIPSI :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 70, -1));

        jLabel4.setText("USERNAME :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, -1));

        jLabel5.setText("NO HP :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, -1));

        jLabel6.setText("GENDER :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, -1));

        jLabel7.setText("ALAMAT :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, -1));

        jLabel8.setText("PESANAN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 60, -1));

        tabel_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "KATEGORI", "KUANTITAS", "UKURAN", "JENIS KAIN", "LINK GAMBAR", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabel_pesanan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 670, 70));

        input_deskripsi.setColumns(20);
        input_deskripsi.setRows(5);
        input_deskripsi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                input_deskripsiPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(input_deskripsi);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 580, 80));
        jPanel1.add(text_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 460, 20));
        jPanel1.add(text_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 460, 20));
        jPanel1.add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 460, 20));
        jPanel1.add(text_no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 460, 20));
        jPanel1.add(text_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 460, 20));

        jLabel9.setText("NAMA PEMESAN :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setText("HARGA :");

        button_tolak.setText("Tolak");
        button_tolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tolakActionPerformed(evt);
            }
        });

        button_terima.setText("Terima");
        button_terima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_terimaActionPerformed(evt);
            }
        });

        input_harga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        input_harga.setName(""); // NOI18N
        input_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_hargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(input_harga))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(0, 478, Short.MAX_VALUE)
                        .addComponent(button_tolak, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_terima, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(input_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_terima, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_tolak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 680, -1));

        button_selesai.setText("SELESAI");
        button_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_selesaiActionPerformed(evt);
            }
        });
        jPanel1.add(button_selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 120, 40));

        button_kembali.setText("<<<");
        button_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(button_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_tolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tolakActionPerformed
        // TODO add your handling code here:
        try {
            penjahit.tolak_pesanan(id);
            this.setVisible(false);
            new Beranda_Penjahit(auth).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Detail_Penjahit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_tolakActionPerformed

    private void button_terimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_terimaActionPerformed
        // TODO add your handling code here:
        try {
            penjahit.terima_pesanan(id, input_harga.getText());
            this.setVisible(false);
            new Beranda_Penjahit(auth).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Detail_Penjahit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_button_terimaActionPerformed

    private void input_deskripsiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_input_deskripsiPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_input_deskripsiPropertyChange

    private void input_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_hargaActionPerformed

    private void button_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_selesaiActionPerformed
        // TODO add your handling code here:
        try {
            penjahit.selesaikan_pesanan(id);
            this.setVisible(false);
            new Beranda_Penjahit(auth).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Detail_Penjahit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_selesaiActionPerformed

    private void button_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kembaliActionPerformed
        // TODO add your handling code here:
        try {
            this.setVisible(false);
            new Beranda_Penjahit(auth).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Detail_Penjahit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Penjahit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Penjahit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Penjahit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Penjahit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_Penjahit(" ", " ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_kembali;
    private javax.swing.JButton button_selesai;
    private javax.swing.JButton button_terima;
    private javax.swing.JButton button_tolak;
    private javax.swing.JTextArea input_deskripsi;
    private javax.swing.JFormattedTextField input_harga;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable tabel_pesanan;
    private javax.swing.JLabel text_alamat;
    private javax.swing.JLabel text_gender;
    private javax.swing.JLabel text_nama;
    private javax.swing.JLabel text_no_hp;
    private javax.swing.JLabel text_username;
    // End of variables declaration//GEN-END:variables
}
